### ISSUE TITLE
V0.11 Scissor not working

### ISSUE THREAD

**Issue by vacarsu** [boydm/scenic#225]
It seems scissor is no longer working after v0.11 update. A direct port of my scrollbar component results in the following.

<img width="699" alt="Screen Shot 2021-07-23 at 12 19 31 PM" src="https://user-images.githubusercontent.com/11384972/126830966-d2a190cf-e973-4d0d-9377-c7a346ad06c8.png">

Notice how the buttons scroll over the header, when they should get cutoff just before the header.

My code which renders the group is exactly the same as it was in v0.10

``` elixir
group(
  graph,
  fn graph ->
    graph
    |> group(
      builder,
      Enum.into(styles, [])
      |> Keyword.put(:id, :content)
      |> Keyword.put(:translate, Vector2.add(state.scroll_position, {content.x, content.y}))
    )
  end,
  scissor: {frame.width, frame.height},
  translate: {frame.x, frame.y}
)
```

**Comment by boydm** [comment]
This is fixed in the v0.11 branch.

If you could confirm, then please add a note and close the issue.

**Comment by vacarsu** [comment]
It is still not working after updating scenic. You can reproduce this in the example app by add this on the components page.

``` elixir
@scissor_example group_spec([@dropdown], translate: {0, 50}, scissor: {100, 100})

# Put them all together
@components [
    # treat the buttons as a group so we can translate them all
    group_spec(@buttons, translate: {0, 10}),
    @slider,
    @radio_group,
    @checkbox,
    @toggle,
    @text_field,
    @password_field,
    @dropdown,
    @scissor_example
  ]
```

**Comment by boydm** [comment]
Hmmm. Hey. As a test, could you go to the Components scene and type way too much text into the TextField control and let me know if that scissors for you or if the text runs over the edge?

**Comment by boydm** [comment]
It works on primitives, but not across the component boundary. Did it used to?

**Comment by vacarsu** [comment]
So looks like TextField to scissor properly. If by component boundary you mean components within a group primitive, yes that used to work.

**Comment by boydm** [comment]
OK. I found it. Just pushed a fix to v0.11 that supports scissor on Component and Script primitives. The rest should be good.

Can you check again please?

**Comment by vacarsu** [comment]
Here is a reproduction repo, I'm still having issues. I've included all the dependencies in the repo so you don't need to do mix deps.get.

https://github.com/vacarsu/scissor_bug

Try passing a text component into the scrollable layout, there is some weirdness going on there. The tooltips when you hover over the buttons on the top right of the modal should also have text in them. it's almost as if the text is getting scissored in a weird way but nothing else is.

``` elixir
|> ScrollLayout.add_to_graph(
        {"Test Scroll", Scenic.Primitive.Text, "Test!!, translate: {100, 100}, fill: :black},
        id: :scroll_layout,
        width: 500,
        height: 600,
        frame_width: 480,
        frame_height: 500,
        content_width: 800,
        content_height: 800,
        show_check: true,
        show_close: true,
        translate: {50, 50}
      )
```

**Comment by boydm** [comment]
Let this sit for a bit with the changes we worked out. Then close if it is working for you.

**Comment by vacarsu** [comment]
Closing, as changes have fixed the issue.
